### Importação das bibliotecas

In [80]:
import pandas as pd
import re
from unidecode import unidecode

### Carregamento dos dados

In [81]:
df = pd.read_json("../data/raw/clientes_crm.json").set_index("code")
df.head(10)

,full_name,location,email
code,,,
1,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",femininos.oliveira.antunes@icloud.com
2,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",nunes.fernanda.soares.azevedo.vieira@outlook.com
3,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",farias.teixeira.daniel.ribeiro#gmail.com
4,Thiago Moreira,"AC , Rio Branco",thiago.moreira#gmail.com
5,Pedro Freitas,PA - Santarém Novo,pedro.freitas#icloud.com
6,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO",coelho.pinheiro.peixoto.antônia.cavalcanti@aol...
7,Bianca Barros Rocha Torres Siqueira,PB/Cabedelo,torres.barros.rocha.bianca.siqueira#aol.com
8,Luiz Alves Pimentel,SE - Aracaju,pimentel.alves.luiz#outlook.com
9,Lucas Guedes Cunha Lopes,PB - João Pessoa,lucas.lopes.guedes.cunha#tutanota.com
10,Débora Paiva,Santarém / PA,paiva.débora#gmx.com

primeira observação é o email, possui acentos e em alguns, no lugar do @ esta um #

In [82]:
df['email'] = df['email'].apply(unidecode).str.replace("#", "@")

df.head(10)

,full_name,location,email
code,,,
1,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",femininos.oliveira.antunes@icloud.com
2,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",nunes.fernanda.soares.azevedo.vieira@outlook.com
3,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",farias.teixeira.daniel.ribeiro@gmail.com
4,Thiago Moreira,"AC , Rio Branco",thiago.moreira@gmail.com
5,Pedro Freitas,PA - Santarém Novo,pedro.freitas@icloud.com
6,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO",coelho.pinheiro.peixoto.antonia.cavalcanti@aol...
7,Bianca Barros Rocha Torres Siqueira,PB/Cabedelo,torres.barros.rocha.bianca.siqueira@aol.com
8,Luiz Alves Pimentel,SE - Aracaju,pimentel.alves.luiz@outlook.com
9,Lucas Guedes Cunha Lopes,PB - João Pessoa,lucas.lopes.guedes.cunha@tutanota.com
10,Débora Paiva,Santarém / PA,paiva.debora@gmx.com

Outro problema é a coluna "location", nela temos um monte de possibilidades com estado e cidade invertendo de posição e separador, irei padronizar isso!

In [83]:
def tratar_location(texto):
    # 1. Remove espaços extras
    texto = texto.strip()
    
    # 2. Padroniza separadores para |
    texto = re.sub(r'\s*[,\-/]\s*', '|', texto)
    
    # 3. Separa as partes
    partes = [parte.strip() for parte in texto.split('|')]
    
    # 4. Identifica qual parte é o estado (2 letras maiúsculas)
    estado = None
    cidade = None
    for parte in partes:
        if re.match(r'^[A-Z]{2}$', parte):
            estado = parte
        else:
            cidade = parte
    
    return pd.Series({'cidade': cidade, 'estado': estado})

In [84]:
df[['cidade', 'estado']] = df['location'].apply(tratar_location)
df = df.drop(columns=['location'])

In [85]:
df.head(10)

,full_name,email,cidade,estado
code,,,,
1,Femininos Oliveira Antunes,femininos.oliveira.antunes@icloud.com,Aratu (Candeias),BA
2,Fernanda Azevedo Soares Nunes Vieira,nunes.fernanda.soares.azevedo.vieira@outlook.com,Recife,PE
3,Daniel Farias Ribeiro Teixeira,farias.teixeira.daniel.ribeiro@gmail.com,Rio Grande,RS
4,Thiago Moreira,thiago.moreira@gmail.com,Rio Branco,AC
5,Pedro Freitas,pedro.freitas@icloud.com,Santarém Novo,PA
6,Antônia Coelho Pinheiro Peixoto Cavalcanti,coelho.pinheiro.peixoto.antonia.cavalcanti@aol...,Fortaleza do Tabocão,TO
7,Bianca Barros Rocha Torres Siqueira,torres.barros.rocha.bianca.siqueira@aol.com,Cabedelo,PB
8,Luiz Alves Pimentel,pimentel.alves.luiz@outlook.com,Aracaju,SE
9,Lucas Guedes Cunha Lopes,lucas.lopes.guedes.cunha@tutanota.com,João Pessoa,PB
10,Débora Paiva,paiva.debora@gmx.com,Santarém,PA

In [86]:
df.isna().sum()

full_name    0
email        0
cidade       0
estado       0
dtype: int64

In [87]:
df.duplicated().sum()

np.int64(0)

In [88]:
df.reset_index(drop=True)

,full_name,email,cidade,estado
0,Femininos Oliveira Antunes,femininos.oliveira.antunes@icloud.com,Aratu (Candeias),BA
1,Fernanda Azevedo Soares Nunes Vieira,nunes.fernanda.soares.azevedo.vieira@outlook.com,Recife,PE
2,Daniel Farias Ribeiro Teixeira,farias.teixeira.daniel.ribeiro@gmail.com,Rio Grande,RS
3,Thiago Moreira,thiago.moreira@gmail.com,Rio Branco,AC
4,Pedro Freitas,pedro.freitas@icloud.com,Santarém Novo,PA
5,Antônia Coelho Pinheiro Peixoto Cavalcanti,coelho.pinheiro.peixoto.antonia.cavalcanti@aol...,Fortaleza do Tabocão,TO
6,Bianca Barros Rocha Torres Siqueira,torres.barros.rocha.bianca.siqueira@aol.com,Cabedelo,PB
7,Luiz Alves Pimentel,pimentel.alves.luiz@outlook.com,Aracaju,SE
8,Lucas Guedes Cunha Lopes,lucas.lopes.guedes.cunha@tutanota.com,João Pessoa,PB
9,Débora Paiva,paiva.debora@gmx.com,Santarém,PA
10,Victor Torres Monteiro,torres.monteiro.victor@gmail.com,Porto Seguro,BA
11,Rafael Pereira Barros,rafael.pereira.barros@zoho.com,Fortaleza do Tabocão,TO
12,Carlos Guimarães Martins,martins.guimaraes.carlos@hotmail.com,Santarém,PA
13,Gabriela Silva Vieira Amaral,vieira.silva.amaral.gabriela@icloud.com,Itacoatiara,AM
14,Carla Lopes Alves Pacheco Rocha,lopes.alves.pacheco.rocha.carla@yahoo.com,Fortaleza do Tabocão,TO
15,Renata Pacheco Cardoso,renata.pacheco.cardoso@zoho.com,Fortaleza,CE
16,Luís Paiva Costa Cardoso Coelho,costa.paiva.luis.coelho.cardoso@aol.com,Corumbá,MS
17,Adriana Guedes Borges Alves Rocha,rocha.adriana.guedes.borges.alves@protonmail.com,Santarém,PA
18,Renata Lima Gomes Coelho Mendonça,renata.lima.mendonca.coelho.gomes@icloud.com,Maceió,AL
19,Bruno Silva,silva.bruno@zoho.com,Santarém Novo,PA
20,Sandra Rocha Oliveira Soares Peixoto,peixoto.soares.rocha.oliveira.sandra@yahoo.com,Rio Branco,AC
21,Daniela Borges Vieira Farias Mendonça,borges.vieira.daniela.mendonca.farias@protonma...,Aracaju,SE
22,Bruna Mendonça Rodrigues,rodrigues.mendonca.bruna@aol.com,Santos,SP
23,Carla Peixoto Azevedo Silva Araújo,peixoto.carla.araujo.silva.azevedo@outlook.com,Laguna,SC
24,Femininos Antunes Lopes Ribeiro Amaral,femininos.antunes.amaral.lopes.ribeiro@icloud.com,São Mateus,ES
25,Luiz Borges Gomes Araújo,gomes.araujo.borges.luiz@hotmail.com,Manaus,AM
26,Flávia Nunes Martins Ribeiro Coelho,nunes.flavia.coelho.martins.ribeiro@protonmail...,Salvador,BA
27,Bianca Rodrigues,rodrigues.bianca@icloud.com,Antonina,PR
28,Gabriela Moraes Macedo Nunes,moraes.nunes.gabriela.macedo@icloud.com,Fortaleza,CE
29,Victor Araújo Azevedo Tavares Correia,araujo.tavares.azevedo.victor.correia@gmail.com,Itacoatiara,AM
30,Jéssica Figueiredo Leite Martins,jessica.martins.leite.figueiredo@tutanota.com,São Luís,MA
31,Daniela Teixeira Antunes Coelho Batista,antunes.coelho.batista.teixeira.daniela@hotmai...,Porto Seguro,BA
32,Diego Costa Guedes Cunha,guedes.cunha.costa.diego@outlook.com,Rio Grande,RS
33,Victor Vieira Nunes Cunha,nunes.cunha.victor.vieira@protonmail.com,Fortaleza,CE
34,Priscila Martins,martins.priscila@tutanota.com,João Pessoa,PB
35,Francisca Ribeiro Pinheiro,ribeiro.francisca.pinheiro@aol.com,Belém,PA
36,Jéssica Pimentel Borges Nunes Teixeira,nunes.borges.teixeira.pimentel.jessica@yahoo.com,Itaqui (São Luís),MA
37,Mateus Antunes,mateus.antunes@gmail.com,Fortaleza do Tabocão,TO
38,Renata Oliveira Siqueira,oliveira.renata.siqueira@aol.com,Suape (Ipojuca),PE
39,Lucas Pacheco,pacheco.lucas@aol.com,Corumbá,MS
40,Pedro Ribeiro Costa Santos Correia,costa.correia.ribeiro.santos.pedro@yahoo.com,Aratu (Candeias),BA
41,Márcia Figueiredo,marcia.figueiredo@protonmail.com,Vila do Conde (Barcarena),PA
42,Jéssica Farias Cunha,farias.jessica.cunha@outlook.com,Itaqui (São Luís),MA
43,Rafael Paiva Vieira,rafael.vieira.paiva@icloud.com,Paranaguá,PR
44,Amanda Santos Figueiredo Rodrigues Siqueira,figueiredo.siqueira.rodrigues.amanda.santos@tu...,Santarém,PA
45,Ana Silva Costa Farias Coelho,costa.farias.coelho.ana.silva@hotmail.com,Macapá,AP
46,Gabriela Barros Lacerda,lacerda.gabriela.barros@tutanota.com,Niterói,RJ
47,Letícia Torres Peixoto Oliveira,torres.oliveira.peixoto.leticia@yahoo.com,Suape (Ipojuca),PE
48,Diego Costa Tavares Antunes,costa.tavares.antunes.diego@icloud.com,Aracaju,SE

Agora está tudo certo!

In [89]:
df.to_csv('../data/processed/clientes_crm_processed.csv', index=False)